FROM node:20-alpine AS builder
ARG VITE_API_URL
ARG VITE_SSE_URL
ARG VITE_AUTHLOCAL_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SSE_URL=$VITE_SSE_URL
ENV VITE_AUTHLOCAL_URL=$VITE_AUTHLOCAL_URL
WORKDIR /app
COPY client/package*.json ./
RUN npm ci
COPY client/. .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
