apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - prisma-push-job.yaml

configMapGenerator:
  - name: hangry-home-server-config
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: hangry-home-server-config
      fieldPath: data.INGRESS_HOST
    targets:
      - select:
          kind: Ingress
          name: hangry-home-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
  - source:
      kind: ConfigMap
      name: hangry-home-server-config
      fieldPath: data.CLIENT_IMAGE
    targets:
      - select:
          kind: Deployment
          name: hangry-home-client
        fieldPaths:
          - spec.template.spec.containers.[name=client].image
  - source:
      kind: ConfigMap
      name: hangry-home-server-config
      fieldPath: data.SERVER_IMAGE
    targets:
      - select:
          kind: Deployment
          name: hangry-home-server
        fieldPaths:
          - spec.template.spec.containers.[name=server].image
      - select:
          kind: Job
          name: hangry-home-prisma-push
        fieldPaths:
          - spec.template.spec.containers.[name=prisma-push].image
